services:
  - type: web
    name: evolution-api
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: API_KEY
        value: yordan232323
      - key: TZ
        value: America/Sao_Paulo
    healthCheckPath: /
